# Generated by Django 4.0.3 on 2022-03-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('roll', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
