# Generated by Django 4.0.3 on 2022-03-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('roll', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.TextField()),
                ('date', models.DateField()),
                ('toMail', models.EmailField(max_length=254)),
                ('fromMail', models.EmailField(max_length=254)),
                ('submittedOn', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
    ]
